name: Build & Release

on:
  workflow_dispatch:
    inputs:
      major-version:
        description: 'Major version tag'
        required: true
        type: string
      minor-version:
        description: 'Minor version tag'
        required: true
        type: string
      patch-version:
        description: 'Patch version tag'
        required: true
        type: string

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set git user
      uses: fregante/setup-git-user@v2
    
    - name: run release script
      run: bash release.sh ${{ github.event.inputs.major-version }} ${{ github.event.inputs.minor-version }} ${{ github.event.inputs.patch-version }}
